spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false #일단 config server 비활성화
  config:
    import: optional:file:./user/.env[.properties] # 모듈 내부 env
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis-stack-compose
      port: 6379
      password: ${REDIS_PASSWORD}


server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버 URL

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

admin:
  token: ${ADMIN_TOKEN}

resilience4j:
  circuitbreaker:
    configs:
      default:  # 기본 구성 이름
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0