management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

spring:
  data:
    redis:
      host: redis-stack-compose
      port: 6379
      password: ${REDIS_PASSWORD}