spring:
  application:
    name: hub-routes-service
  cloud:
    config:
      enabled: false #일단 config server 비활성화
  config:
    import: optional:file:./hub-routes/.env[.properties] # 모듈 내부 env
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 19099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버 URL

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

kakao:
  api:
    key: ${KAKAO_MAP_KEY}