server:
  port: 19099

spring:
  cloud:
    config:
      enabled: false
  config:
    import:
#      - optional:file:./hub/env/db.env[.properties]
      - optional:file:../.env
  application:
    name: hub-routes-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/sibijo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true   # ?????? Eureka? ?? ??? ??
    fetch-registry: true         # ?? ??? ??(Eureka ?????)? ???

kakao:
  api:
    key: 9177b1d8e0e9ad5c8d3ad7ac72a869b7

jwt:
  secret:
    key: VAV3VGIhTYM8g3zY5vwLMPCYlsbW/PsSW+j+YLEiODAS0N/tOch/dvbnDAVLqz6xlqBSEmgpabEaD5mGxVWSMA==