server:
  port: 19096

spring:
  cloud:
    config:
      enabled: false
  config:
    import:
      - optional:file:env/db.env[.properties]
      - optional:file:env/security.env[.properties]
  application:
    name: product-service  # Eureka에 등록될 서비스 이름
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:19090/eureka/

company:
  service:
    url: http://company-service
