spring:
  application:
    name: gateway-service
  config:
    import: optional:file:./gateway/.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
  data:
    redis:
      host: redis-stack-compose
      port: 6379
      password: ${REDIS_PASSWORD}

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버 URL

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: user-service
        url: /swagger/user-service/v3/api-docs



