spring:
  application:
    name: gateway-service
  config:
    import: optional:file:./gateway/.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
      routes:
        - id: user-service  # 라우트 식별자
          uri: lb://user-service # 'user-service'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/users/**, /api/delivery-agents/** # /users/** 경로로 들어오는 요청을 이 라우트로 처리
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/hubs/**

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버 URL

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}